//
//  LocalizedExpertise+CoreDataProperties.swift
//  
//
//  Created by Peter van den Hamer on 29/07/2026.
//
//  Generated by Xcode originally. Codegen is now Manual/None, so this file is maintained by hand (see README).
//

public import Foundation
public import CoreData

public typealias LocalizedExpertiseCoreDataPropertiesSet = NSSet

extension LocalizedExpertise {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<LocalizedExpertise> {
        return NSFetchRequest<LocalizedExpertise>(entityName: "LocalizedExpertise")
    }

    @NSManaged nonisolated public var name_: String?
    @NSManaged nonisolated public var usage: String?
    @NSManaged nonisolated public var expertise_: Expertise?
    @NSManaged nonisolated public var language_: Language?

}

extension LocalizedExpertise : Identifiable {

}
