//
//  LocalizedRemark+CoreDataClass.swift
//  
//
//  Created by Peter van den Hamer on 29/07/2026.
//
//  Generated by Xcode originally. Codegen is now Manual/None, so this file is maintained by hand (see README).
//

public import Foundation
public import CoreData

public typealias LocalizedRemarkCoreDataClassSet = NSSet

@objc(LocalizedRemark)
public class LocalizedRemark: NSManagedObject {

}
