//
//  Photo_Club_Hub+CoreDataModel.swift
//  
//
//  Created by Peter van den Hamer on 29/07/2026.
//
//  Generated by Xcode originally. Codegen is now Manual/None, so this file is maintained by hand (see README).
//

public import Foundation
public import CoreData

public typealias PhotoClubHubFoundationFrameworkSet = NSSet
public typealias PhotoClubHubCoreDataFrameworkManagedObject = NSManagedObject
